[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.5.5",
    "docx>=0.2.4",
    "openai>=1.86.0",
    "pypdf2>=3.0.1",
    "python-docx>=1.1.2",
]
